### ISSUE TITLE
Add some bats tests for the scripts

### ISSUE THREAD

**Issue by assimovt** [unacast/actions#10]
GitHub actions repo uses [bats](https://github.com/sstephenson/bats) to test the shell scripts - would be nice to follow conventions and some tests.

**Comment by heim** [comment]
@assimovt, do you have any suggestions on how to structure such a test suite? We'd need a mock `github_event.json`, and probably a mock api to hit.

**Comment by judoole** [comment]
@heim seems like perhaps this one does something along the same lines as we would like to do https://github.com/actions/bin/blob/master/filter/test/merged.bats ?

**Comment by heim** [comment]
Closing this now, as some (basic) tests are in place.
